nodeLinker: pnp
defaultSemverRangePrefix: ""
yarnPath: .yarn/releases/yarn-3.6.1.cjs
enableScripts: false

supportedArchitectures:
  os:
    - darwin
    - linux
  arch:
    - arm64
    - x64

packageExtensions:
  "@jest/globals@^27.0.0":
    dependencies:
      "@jest/types": "*"
