yarnPath: .yarn/releases/yarn-3.6.1.cjs

nodeLinker: pnp
defaultSemverRangePrefix: ""
enableScripts: false

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

packageExtensions:
  "hast-util-from-html@*":
    dependencies:
      "vfile-message": "^3.0.0"
