nodeLinker: pnp
defaultSemverRangePrefix: ""
yarnPath: .yarn/releases/yarn-3.6.1.cjs
enableScripts: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

packageExtensions:
  "@jest/globals@^27.0.0":
    dependencies:
      "@jest/types": "*"
