nodeLinker: pnp
defaultSemverRangePrefix: ""
yarnPath: .yarn/releases/yarn-3.6.1.cjs
enableScripts: false

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - glibc
  os:
    - current
    - darwin
    - linux
    - win32
