nodeLinker: pnp
defaultSemverRangePrefix: ""
yarnPath: .yarn/releases/yarn-3.6.1.cjs
enableScripts: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux


packageExtensions:
  "gatsby-plugin-sharp@*":
    dependencies:
      sharp: "*"
  "gatsby-plugin-sharp-virtual@*":
    dependencies:
      sharp: "*"
  "gatsby-transformer-sharp@*":
    dependencies:
      sharp: "*"
  "gatsby-image@*":
    dependencies:
      sharp: "*"
