name: Check Changesets Update Note

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          node-version-file: ".nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.12

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Check for specific label
        run: |
          label_name="pass-check"
          pr_labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }} | jq -r '.labels[].name')
          if echo "$pr_labels" | grep -q "$label_name"; then
            echo "LABEL_FOUND=true" >> $GITHUB_ENV
          else
            echo "LABEL_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Check changesets
        if: env.LABEL_FOUND == 'false'
        run: |
          if [[ "${{ github.head_ref }}" == *changeset-release/* ]]; then
            echo "Branch name contains changeset-release/, passing the check."
            exit 0
          fi

          if [[ ! $(find .changeset -name '*.md' ! -name 'README.md') ]]; then
            echo "No MD files other than README.md found in .changesets folder, failing the check."
            exit 1
          fi
          echo "Check passed."
