name: Check Changesets Update Note

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 코드를 체크아웃하고 있어요.
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0


      - name: pnpm을 설정하고 있어요.
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.12

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-


      - name: 노드를 설정하고 있어요.
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: pass-check 라벨을 확인하고 있어요.
        run: |
          label_name="pass-check"
          pr_labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }} | jq -r '.labels[].name')
          if echo "$pr_labels" | grep -q "$label_name"; then
            echo "LABEL_FOUND=true" >> $GITHUB_ENV
          else
            echo "LABEL_FOUND=false" >> $GITHUB_ENV
          fi

      - name: changeset-release 브랜치인지 확인하고 있어요.
        if: env.LABEL_FOUND == 'false'
        run: |
          if [[ "${{ github.head_ref }}" == *changeset-release/* ]]; then
            echo "Branch name contains changeset-release/, passing the check."
            exit 0
          fi

          if [[ ! $(find .changeset -name '*.md' ! -name 'README.md') ]]; then
            echo "No MD files other than README.md found in .changesets folder, failing the check."
            exit 1
          fi
          echo "Check passed."
