name: Test Changed Packages with Turbo on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.get-changed-dirs.outputs.changed_dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of changed directories
        id: get-changed-dirs
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | \
                 grep '/.*$' | \
                 sed -E 's@(.*)/@\1@' | \
                 sort | \
                 uniq)
          echo "Changed directories: $dirs"
          echo "::set-output name=changed_dirs::$dirs"

  test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{fromJson(needs.detect-changes.outputs.changed_dirs)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests in changed directory
        run: |
          cd ${{ matrix.dir }}
          yarn test

      - name: Test Report for ${{ matrix.dir }}
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results-${{ matrix.dir }}
          path: ${{ matrix.dir }}/junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
