name: Test Changed Packages with Turbo on PR


on:
  pull_request:
    branches:
      - feature/*

jobs:
  jest-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ base, util, hook, lint, shopl-ui, hada-ui ]  # 패키지 이름 목록

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Test changed packages with Turbo and save results
        run: yarn turbo run test:report

      - name: Test Report for ${{ matrix.package }}
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results-${{ matrix.package }}
          path: packages/${{ matrix.package }}/junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
