name: Test Changed Packages with Turbo on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detect packages with junit.xml
        id: detect-packages
        run: |
          packages=$(find . -name 'junit.xml' -exec dirname {} \; | sed 's|.*/||' | jq -R -s -c 'split("\n")[:-1]')
          echo "Detected packages: $packages"
          echo "::set-output name=packages::$packages"

      - name: Set matrix for next job
        id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.detect-packages.outputs.packages }}"

  test-report:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Report for ${{ matrix.package }}
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results-${{ matrix.package }}
          path: */${ { matrix.package } }/junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
