name: Test Changed Packages with Turbo on PR

on:
  pull_request:
    branches:
      - feature/*
    types:
      - opened
      - synchronize

jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Turbo로 변경된 패키지만 테스트하고 있어요.
        run: yarn turbo run test --since=origin/main

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          path: '**/junit.xml'
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
