name: Test Changed Packages with Turbo on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detect junit.xml paths
        id: detect-paths
        run: |
          paths=$(find . -name 'junit.xml' -printf '\"%p\",\n' | sed '$s/,$//')
          matrix="{\"path\": [$paths]}"
          echo "Matrix: $matrix"
          echo "::set-output name=matrix::$matrix"

  test-report:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Report for ${{ matrix.path }}
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results-${{ matrix.path }}
          path: ${{ matrix.path }}
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
